namespace Shared;

/// <summary>
/// Represents a trading signal generated by a strategy
/// </summary>
public class StrategySignal
{
    /// <summary>
    /// Unix timestamp when signal was generated
    /// </summary>
    public long Timestamp { get; set; }

    /// <summary>
    /// Option ticker symbol
    /// </summary>
    public string Ticker { get; set; } = string.Empty;

    /// <summary>
    /// Type of signal
    /// </summary>
    public SignalType SignalType { get; set; }

    /// <summary>
    /// Price at which signal was generated
    /// </summary>
    public double Price { get; set; }

    /// <summary>
    /// Optional: Quantity to trade
    /// </summary>
    public int Quantity { get; set; } = 1;

    /// <summary>
    /// Optional: Reason for the signal (for debugging/analysis)
    /// </summary>
    public string Reason { get; set; } = string.Empty;

    /// <summary>
    /// DateTime representation of the timestamp (UTC)
    /// </summary>
    public DateTime DateTime => DateTimeOffset.FromUnixTimeMilliseconds(Timestamp).UtcDateTime;
}

public enum SignalType
{
    HOLD,
    BUY,
    SELL
}
